@del /q gnulib.lib
call comp L_eprintf
call comp L_umulsi3
call comp L_mulsi3
call comp L_udivsi3
call comp L_divsi3
call comp L_umodsi3
call comp L_modsi3
call comp L_lshrsi3
call comp L_lshlsi3
call comp L_ashrsi3
call comp L_ashlsi3
call comp L_divdf3
call comp L_muldf3
call comp L_negdf2
call comp L_adddf3
call comp L_subdf3
call comp L_cmpdf2
call comp L_fixunsdfsi
call comp L_fixdfsi
call comp L_floatsidf
call comp L_addsf3
call comp L_negsf2
call comp L_subsf3
call comp L_cmpsf2
call comp L_fixunsdfsi
call comp L_fixdfsi
call comp L_floatsidf
call comp L_addsf3
call comp L_negsf2
call comp L_subsf3
call comp L_cmpsf2
call comp L_mulsf3
call comp L_divsf3
call comp L_truncdfsf2
call comp L_extendsfdf2
call comp L_bb
call comp L_builtin_new
call comp L_builtin_New2
call comp L_builtin_del
lib32 -subsystem:posix -machine:i386 -out:gnulib.lib *.obj
@del /q *.obj
